//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileHashCraft.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileHashCraft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonExecuteCommand {
            get {
                return ResourceManager.GetString("ButtonExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash calculation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonHashCalc {
            get {
                return ResourceManager.GetString("ButtonHashCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash Management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonHashManagement {
            get {
                return ResourceManager.GetString("ButtonHashManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonModify {
            get {
                return ResourceManager.GetString("ButtonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to standard settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonNormalSettings {
            get {
                return ResourceManager.GetString("ButtonNormalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash acquisition target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTargetFilter {
            get {
                return ResourceManager.GetString("ButtonTargetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-256 (High security: More reliable, generally faster than MD5. Recommended as standard) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA256 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-384 (High security: higher security strength than SHA-256, but slower computation) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA384 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-512 (maximum security: very high security strength, but slow computation) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA512 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCommand {
            get {
                return ResourceManager.GetString("LabelCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of all files to get hash : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCountAllFilesGetHash {
            get {
                return ResourceManager.GetString("LabelCountAllFilesGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files for which a hash has already been obtained に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCountAlreadyGetHash {
            get {
                return ResourceManager.GetString("LabelCountAlreadyGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files to get hashes from filtered files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCountFilteredGetHash {
            get {
                return ResourceManager.GetString("LabelCountFilteredGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files requiring hash acquisition : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCountRequireGetHash {
            get {
                return ResourceManager.GetString("LabelCountRequireGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCurrentDirectory {
            get {
                return ResourceManager.GetString("LabelCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Scanning : Dicrecotires に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDirectoryCount {
            get {
                return ResourceManager.GetString("LabelDirectoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory Scanning...: Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDirectoryScanning {
            get {
                return ResourceManager.GetString("LabelDirectoryScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For Advanced User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert {
            get {
                return ResourceManager.GetString("LabelExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whether to delete empty directories or not に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_EmptyDirDelete {
            get {
                return ResourceManager.GetString("LabelExpert_EmptyDirDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target hidden files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_HiddenFiles {
            get {
                return ResourceManager.GetString("LabelExpert_HiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target read-only files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_ReadOnlyFiles {
            get {
                return ResourceManager.GetString("LabelExpert_ReadOnlyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whether to delete files of size 0 or not に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_ZeroSizeFileDelete {
            get {
                return ResourceManager.GetString("LabelExpert_ZeroSizeFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifying file types by extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtention_FilterSetting {
            get {
                return ResourceManager.GetString("LabelExtention_FilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify files by file type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtention_GroupFilterSetting {
            get {
                return ResourceManager.GetString("LabelExtention_GroupFilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Applications {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Archives {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Documents {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Movies {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Have Extentions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_NoHaveExtentions {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_NoHaveExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ohter Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_OtherFiles {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_OtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Pictures {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Registrations {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Sounds {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source Code Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_SourceCodes {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_SourceCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm for file hash calculation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFileHashAlgorithmString {
            get {
                return ResourceManager.GetString("LabelFileHashAlgorithmString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFinished {
            get {
                return ResourceManager.GetString("LabelFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFontSizeString {
            get {
                return ResourceManager.GetString("LabelFontSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFontString {
            get {
                return ResourceManager.GetString("LabelFontString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression Search Criteria に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegex_Criteria {
            get {
                return ResourceManager.GetString("LabelRegex_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression Search Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegex_Error {
            get {
                return ResourceManager.GetString("LabelRegex_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   During internal file writing or other processing of found files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Search Criteria に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcard_Criteria {
            get {
                return ResourceManager.GetString("LabelWildcard_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcard_Error {
            get {
                return ResourceManager.GetString("LabelWildcard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard search criteria not entered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcardError_Empty {
            get {
                return ResourceManager.GetString("LabelWildcardError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Characters not allowed in file names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcardError_NotAllowedCharacter {
            get {
                return ResourceManager.GetString("LabelWildcardError_NotAllowedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too much use of &apos;*&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcardError_TooManyAsterisk {
            get {
                return ResourceManager.GetString("LabelWildcardError_TooManyAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewDataModified {
            get {
                return ResourceManager.GetString("ListViewDataModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewName {
            get {
                return ResourceManager.GetString("ListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewSize {
            get {
                return ResourceManager.GetString("ListViewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewType {
            get {
                return ResourceManager.GetString("ListViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Have Extention  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoHaveExtentions {
            get {
                return ResourceManager.GetString("NoHaveExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Caution) Advanced Settings(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentExpert {
            get {
                return ResourceManager.GetString("TabContentExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression Settings(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentRegularExpression {
            get {
                return ResourceManager.GetString("TabContentRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard Settings(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentStarndard {
            get {
                return ResourceManager.GetString("TabContentStarndard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Settings(_W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentWildCard {
            get {
                return ResourceManager.GetString("TabContentWildCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Filter Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleTargetFilterWindow {
            get {
                return ResourceManager.GetString("TitleTargetFilterWindow", resourceCulture);
            }
        }
    }
}
