//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileHashCraft.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileHashCraft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Execute Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonExecuteCommand {
            get {
                return ResourceManager.GetString("ButtonExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash Management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonHashManagement {
            get {
                return ResourceManager.GetString("ButtonHashManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MD5 (Low Security: Prone to collision risks, deprecated. Tends to be fast on HDDs.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_MD5 {
            get {
                return ResourceManager.GetString("HashAlgorithm_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-256 (High security: reliable, runs fast enough, faster than MD5 on some storage. Recommended as standard) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA256 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-384 (High Security: Higher security strength than SHA-256, but computations are slower) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA384 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-512 (Maximum Security: Very high security strength, but computations are very slow) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA512 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCommand {
            get {
                return ResourceManager.GetString("LabelCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCurrentDirectory {
            get {
                return ResourceManager.GetString("LabelCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm for file hash calculation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFileHashAlgorithmString {
            get {
                return ResourceManager.GetString("LabelFileHashAlgorithmString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFontSizeString {
            get {
                return ResourceManager.GetString("LabelFontSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFontString {
            get {
                return ResourceManager.GetString("LabelFontString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewDataModified {
            get {
                return ResourceManager.GetString("ListViewDataModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewName {
            get {
                return ResourceManager.GetString("ListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewSize {
            get {
                return ResourceManager.GetString("ListViewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewType {
            get {
                return ResourceManager.GetString("ListViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
    }
}
